name: Run R Script Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:  # Allows manual trigger

env:
  # Path to shiny folder on server to deploy to
  core-prod-path: ${{ github.ref == 'refs/heads/main' && '/deploy/risk-map' }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1'  # Use the appropriate R version

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("jsonlite", "devtools"))'

      - name: Run R Script
        env:
          SENSINGCLUES_USERNAME: ${{ secrets.SCA_USERNAME }}
          SENSINGCLUES_PASSWORD: ${{ secrets.SCA_PASSWORD }}
        run: Rscript charcoal_observations.R

      - name: Upload CSV Output
        uses: actions/upload-artifact@v3
        with:
          name: charcoal-data
          path: charcoal_observations_*.csv

      - name: Commit and Push CSV File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add charcoal_observations_*.csv || echo "No changes to commit"
          git diff --cached --exit-code || git commit -m "Add monthly charcoal observations"
          git push || echo "No changes to push"

      - name: Define Deployment Path
        id: define-path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "DEPLOY_PATH=/deploy/risk-map" >> $GITHUB_ENV
          else
          echo "test"
          fi
        #echo "DEPLOY_PATH=/deploy/test-env" >> $GITHUB_ENV

      - name: Move CSV Output to Deployment Path (Local Server)
        run: |
          mkdir -p $DEPLOY_PATH
          mv charcoal_observations_*.csv $DEPLOY_PATH/
          echo "CSV output saved in $DEPLOY_PATH"