name: Run R Script Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SENSINGCLUES_USERNAME: ${{ secrets.SENSINGCLUES_USERNAME }}
      SENSINGCLUES_PASSWORD: ${{ secrets.SENSINGCLUES_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1'  # Use the appropriate R version

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("jsonlite", "devtools"))'

      - name: Run R Script
        run: Rscript charcoal_observations.R

      - name: Upload CSV Output
        uses: actions/upload-artifact@v3
        with:
          name: charcoal-data
          path: charcoal_observations_*.csv

      - name: Commit and Push CSV File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add charcoal_observations_*.csv
          git commit -m "Add monthly charcoal observations"
          git push

      - name: Move CSV Output to Server Directory
        run: |
          mkdir -p /opt/data-reports  # Change to your preferred directory
          mv charcoal_observations_*.csv /opt/data-reports/
          echo "CSV output saved in /opt/data-reports/"